services:
  is-my-burguer-pagamento:
    container_name: is-my-burguer-pagamento
    image: docker.io/ismaelgcosta/is-my-burguer-pagamento:is-my-burguer-pagamento-2.1.4
    environment:
      - SERVICE_DISCOVERY_USERNAME
      - SERVICE_DISCOVERY_PASSWORD
      - MONGODB_HOST
      - MONGODB_PASSWORD
      - MONGODB_USER
      - CLIENT_DOMAIN
      - AWS_REGION
      - AWS_COGNITO_USER_POOL_ID
    build:
        dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8743:8743'
    restart: unless-stopped
    networks:
      - ismyburguer-backend

networks:
  ismyburguer-backend:
    external: false
    driver: bridge